name: li_webview
description: Yet another web view plugin
version: 0.0.2
author: Lucky Intelligence S.A.P.I. de C.V. <developer@luckyintelligence.com>
homepage: http://luckyintelligence.com
repository: https://github.com/lucky-intelligence/li_webview

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  plugin:
    androidPackage: com.luckyintelligence.li_webview
    pluginClass: LiWebviewPlugin